kind: pipeline
name: go-1-11

steps:
- name: test
  image: golang:1.11
  commands:
  - go get -t -d -v
  - go test -v

- name: slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack_secret
    channel: prj-validator-drone
    username: Drone CI
  when:
    status: [success, failure]

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: go-1-10

steps:
- name: test
  image: golang:1.10
  commands:
  - go get -t -d -v
  - go test -v

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_secret
    channel: prj-validator-drone
    username: Drone CI
  when:
    status: [success, failure]

trigger:
  branch:
  - master
  event:
  - push
