kind: pipeline
name: go-1-11

steps:
- name: test
  image: golang:1.11
  settings:
    webhook: slack_secret
    channel: pri-validator-drone
    usernam: Drone CI
  when:
    status: [success, failure]
  commands:
  - go get -t -d -v
  - go test -v

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: go-1-10

steps:
- name: test
  image: golang:1.10
  settings:
    webhook: slack_secret
    channel: pri-validator-drone
    usernam: Drone CI
  when:
    status: [success, failure]
  commands:
  - go get -t -d -v
  - go test -v

trigger:
  branch:
  - master
  event:
  - push
