kind: pipeline
name: go-1-11

steps:
- name: test
  image: golang:1.11
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: dev
  when:
    status: [success, failure]
  commands:
  - go get -t -d -v
  - go test -v

---
kind: pipeline
name: go-1-10

steps:
- name: test
  image: golang:1.10
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: dev
  when:
    status: [success, failure]
  commands:
  - go get -t -d -v
  - go test -v
